name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write   # 必须
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 修改文件路径（直接在源文件上改）
        run: |
          find . -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) \
            -exec sed -i 's|\(["'\'']\)\(\.\.\/\)\?\(css\|js\|img\|assets\|static\|fonts\|media\|uploads\|files\|data\|json\|lib\|vendor\|plugins\|js/modules\)/|\1/project/\3/|g' {} +

      - name: Commit 修改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update asset paths for pages"
          file_pattern: "*.html *.css *.js"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'     # 直接部署当前目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4